# [START appengine_websockets_yaml]
runtime: nodejs
env: flex

# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.
resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3

network:
  session_affinity: true
# [END appengine_websockets_yaml]